version: "3.7"
services:

    database:
        build:
            context: ./mariadb
        env_file: ./mariadb/mariadb.env
        volumes:
            - /data/airflow_db:/mnt/mysql
        networks:
            backend:

    redis:
        build:
            context: ./redis
        command: redis-server /data/redis.conf
        networks:
            backend:
                ipv4_address: 172.18.0.11

    airflow-scheduler:
        build:
            context: ./airflow
        env_file: ./airflow/airflow.env
        user: airflow
        command: /bin/bash -c "airflow initdb && airflow scheduler"
        expose:
            - "8000"
            - "8001"
        volumes:
            - /data/airflow/dags:/airflow/dags
            - /data/airflow/logs:/airflow/logs
        depends_on:
            - database
            - redis
        networks:
            backend:
                ipv4_address: 172.18.0.10

    airflow-web:
        build:
            context: ./airflow
        env_file: ./airflow/airflow.env
        user: airflow
        command: airflow webserver
        expose:
            - "8000"
        volumes:
            - /data/airflow/dags:/airflow/dags
            - /data/airflow/logs:/airflow/logs
        depends_on:
            - database
            - redis
            - airflow-scheduler
        networks:
            frontend:
                ipv4_address: 173.17.0.10
            backend:

    airflolw-worker:
        build:
            context: ./airflow
        env_file: ./airflow/airflow.env
        volumes:
            - /data/airflow/dags:/airflow/dags
            - /data/airflow/logs:/airflow/logs
        depends_on:
            - database
            - redis
            - airflow-scheduler
        user: airflow
        command: airflow worker
        networks:
            backend:

networks:
    frontend:
        ipam:
            driver: default
            config:
                - subnet: 173.17.0.0/24
    backend:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/24
